# Generated by Django 3.2.4 on 2021-06-13 14:22

from django.db import migrations, models
import moviesapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('movieID', moviesapi.models.TruncatingCharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Title', models.TextField()),
                ('Year', moviesapi.models.TruncatingCharField(default='N/A', max_length=4)),
                ('Rated', moviesapi.models.TruncatingCharField(default='N/A', max_length=10)),
                ('Released', moviesapi.models.TruncatingCharField(default='N/A', max_length=20)),
                ('Runtime', moviesapi.models.TruncatingCharField(default='N/A', max_length=20)),
                ('Genre', models.TextField(default='N/A')),
                ('Director', moviesapi.models.TruncatingCharField(default='N/A', max_length=100)),
                ('Writer', moviesapi.models.TruncatingCharField(default='N/A', max_length=100)),
                ('Actors', moviesapi.models.TruncatingCharField(default='N/A', max_length=200)),
                ('Plot', models.TextField(default='N/A')),
                ('Language', moviesapi.models.TruncatingCharField(default='N/A', max_length=100)),
                ('Country', moviesapi.models.TruncatingCharField(default='N/A', max_length=200)),
                ('Awards', moviesapi.models.TruncatingCharField(default='N/A', max_length=200)),
                ('Poster', models.TextField(default='N/A')),
                ('Ratings', moviesapi.models.TruncatingCharField(default='N/A', max_length=500)),
                ('Metascore', moviesapi.models.TruncatingCharField(default='N/A', max_length=10)),
                ('imdbRating', moviesapi.models.TruncatingCharField(default='N/A', max_length=10)),
                ('imdbVotes', moviesapi.models.TruncatingCharField(default='N/A', max_length=20)),
                ('imdbID', moviesapi.models.TruncatingCharField(max_length=20, primary_key=True, serialize=False)),
                ('Type', moviesapi.models.TruncatingCharField(default='N/A', max_length=20)),
                ('DVD', moviesapi.models.TruncatingCharField(default='N/A', max_length=20)),
                ('BoxOffice', moviesapi.models.TruncatingCharField(default='N/A', max_length=20)),
                ('Production', moviesapi.models.TruncatingCharField(default='N/A', max_length=60)),
                ('Website', moviesapi.models.TruncatingCharField(default='N/A', max_length=60)),
            ],
        ),
    ]
